### ISSUE TITLE
Db module like config parameters

### ISSUE THREAD

**Issue by tanakahisateru** [Ippey/quickbrownfox-codeception-helper#2]
Codeception's [Db module](https://codeception.com/docs/09-Data) uses `dsn`, `user` and `password` parameters for configuration. I want to do the same way also for this module.

```
modules:
    config:
        Db:
            dsn: 'PDO DSN HERE'
            user: 'root'
            password:
        QuickBrownFoxHelper:
            dsn: 'PDO DSN HERE'
            user: 'root'
            password:
```
