### ISSUE TITLE
Remove composer.lock

### ISSUE THREAD

**Issue by tanakahisateru** [Ippey/quickbrownfox-codeception-helper#3]
I suggest to remove `composer.lock` and to ignore it because Composer doesn't use `lock` file when package installation. I prefer semantic version constraints instead.

TraviceCI can test sub package dependencies for both of latest version and lowest one. You can check if version constraint is appropriate or not.

```yaml
language: php
php:
  - 5.6
  - 7
  - 7.1
  - 7.2
env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest"
before_script:
  - composer update $DEPENDENCIES
script:
  - ...
```
