### ISSUE TITLE
Retain single FixtureManager while testing 

### ISSUE THREAD

**Issue by tanakahisateru** [Ippey/quickbrownfox-codeception-helper#5]
https://github.com/Ippey/quickbrownfox-codeception-helper/blob/88e7bba12108316cf928f4b3004b20623659c3fb/src/QuickBrownFoxHelper.php#L49

Initializing FixtureManager for every tests costs much. What's needed is new instance of FixtureSetupSession created by SessionManager. I prefer call `new FixtureManager()` only once.

FixtureManager also can manage reusable predefined/named data generators. There may be such future idea:

```yaml
modules:
    config:
        QuickBrownFoxHelper:
            # ...
            initScript:  some/config/path/qbf-init.php
```

```php
/** @var Connection $connection DBAL **/
// Any initialization such as additinal type mapping
$connection->getDatabasePlatform()->registerDoctrineTypeMapping('hoge', 'string');
$connection->... ;

/** @var FixtureManager $fixtureManager QBF **/
// Define common data pattern
$fixtureManager->table('my_table', function ($td) {
    $td->generator('DataPatternA')->define(function($i) {
       return [ ... ];
    });
    $td->generator('DataPatternB')->define(function($i) {
       return [ ... ];
    });
});

// Usage:
// $this->tester->getFixtureSession()
//    ->into('my_table')->with('DataPatternA')->generate(100);
```
